import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  main: {
    flex: 1,
  },
  backBtn: {
    marginLeft: 17,
    marginTop: 38,
  },
  signUpHead: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 22,
    marginTop: 31,
    marginLeft: 114,
  },
  fullNameInput: {
    borderColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 33,
    fontSize: 17,
    paddingLeft: 30,
    fontWeight: '100',
    height: 57,
    color: '#FFFFFF',
  },
  emailInput: {
    borderColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 20,
    fontSize: 17,
    paddingLeft: 30,
    fontWeight: '200',
    height: 57,
    color: '#FFFFFF',
  },
  passwordInput: {
    borderColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 20,
    fontSize: 17,
    paddingLeft: 30,
    fontWeight: '100',
    height: 57,
    color: '#FFFFFF',
  },
  btnBackGrondLiner: {
    height: 85,
    marginHorizontal: 16,
    marginTop: 25,
  },
  resetBtn: {
    height: 65,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    borderBottomLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: 10,
  },
  btntext: {
    color: '#24000B',
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
    paddingTop: 22,
  },
  mainDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 50,
    // position: 'absolute',
    // left: 0,
    // bottom: 0,
    // right: 0,
  },
  divider: {
    flex: 1,
    height: 0.5,
    backgroundColor: 'white',
  },
  dividerText: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '100',
    marginHorizontal: 20,
  },
  socialContent: {
    flexDirection: 'row',
    marginTop: 40,
    justifyContent: 'space-evenly',
  },
  dropdownView: {
    flexDirection: 'row',
    marginHorizontal: 20,
    justifyContent: 'space-between',
  },
  dropDownContainer: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    height: 57,
    width: 150,
    fontSize: 16,
    marginTop: 20,
  },
  placeholder: {
    fontSize: 17,
    color: 'white',
    paddingLeft: 15,
    fontWeight: '100',
  },
});
